### ISSUE TITLE
Panic when adding a node to a child

### ISSUE THREAD

**Issue by simonpenel** [onecodex/taxonomy#34]
Hi, I just start to learn Rust, so I apologize if my question is stupid!
I encounter a problem when building a tree by adding nodes to the root then adding nodes its children:
 
   let mut arbrevide =  taxonomy::GeneralTaxonomy::default();
   arbrevide.add(0,"Gauche").expect("Impossible d'ajouter un noeud");
    arbrevide.add(0,"Droite").expect("Impossible d'ajouter un noeud");
    // arbrevide.remove(1).expect("Impossible de supprimer un noeud"); // a remettre
    println!("ARBRE VIDE  = {:?}",arbrevide);
    println!(">>>TAXIDS = {:?}",arbrevide.tax_ids);
    println!(">>>LONGUEUR = {}",arbrevide.tax_ids.len());
    arbrevide.add(1,"Super").expect("Impossible d'ajouter un noeud");

There is a panic signal when I try to add a node to the node with an internal_taxid equal to 1
Note that if the line  
`arbrevide.remove(1).expect("Impossible de supprimer un noeud");`
is uncommented, it works fine....

I understand that there is a problem at the children_lookup level...

What is the correct way to build a tree then?

thanks for your help

all the best
Simon

**Comment by Keats** [comment]
So it looks like we don't actually check if the parent exists before trying to add the new node. This should return an error instead of a out of bound panics. I'll fix it soonish

**Comment by simonpenel** [comment]
Thanks a lot!!
( It seems to me that the parent exists in my code? Maybe I missed something) 
all the best,
Simon

**Comment by Keats** [comment]
It's in the `children_lookup` that we are not inserting it when calling with `GeneralTaxonomy::default()`. We don't really use that method at all in our code except in one test so I guess it was easy to miss. We mostly load existing ones via https://github.com/onecodex/taxonomy#loading-a-taxonomy

**Comment by Keats** [comment]
With https://github.com/onecodex/taxonomy/pull/39 ?

**Comment by audy** [comment]
@Keats yep, from `fixes`:

```python
In [1]: import taxonomy

In [2]: tax =taxonomy.Taxonomy.from_ncbi("ncbi_taxonomy")

In [3]: tax.add_node('2', '10000000001')

In [4]: tax.add_node('10000000001', '10000000002')
thread '<unnamed>' panicked at 'index out of bounds: the len is 2423674 but the index is 2423674', src/base.rs:209:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Keats** [comment]
This should be fixed in the `fixes` branch
