### ISSUE TITLE
Taxonomy from python nested dictionary

### ISSUE THREAD

**Issue by GiorgioBarnabo** [onecodex/taxonomy#44]
Hi there,

is there any easy way to create a taxonomy from a python nested dictionary?
For instance, I would like to turn: {'tax': {'a':{'c':{}, 'd':{}}, 'b': {'e':{}, 'f':{}}}}

tax
--- a
------- c
------- d
--- b
------- e
------- f

In general, I do not understand what format **Taxonomy.from_json(value: str, /, json_pointer: str)** takes as input. Could you please provide some examples? It there any online editor to first design the taxonomy with nodes and arrows and then export it in the right format?

Thank you.

**Comment by Keats** [comment]
I'll add some examples soonish but you can look at the tests to see what's supported: https://github.com/onecodex/taxonomy/blob/master/src/formats/json.rs#L403

There are 2 formats supported:
1. node links
2. tree

I don't recommend node links as it can be messy compared to a simple tree. As for ` Taxonomy.from_json(value: str, /, json_pointer: str) `, `value` is the JSON string and `json_pointer` is an optional json pointer to where the taxonomy data is located if the `value` data has other fields (eg something `{"name": "taxonomy", "taxonomy": {}}`, you can point to the `taxonomy` field. You could also do `Taxonomy.from_json(value["taxonomy"])` in  that case.

I'll try to add examples this week

**Comment by Keats** [comment]
Is https://github.com/onecodex/taxonomy/pull/45/files clearer for the input?
