### ISSUE TITLE
No source distribution for Taxonomy 0.10.0 or wheels for any version with Python 3.12

### ISSUE THREAD

**Issue by warrickball** [onecodex/taxonomy#57]
I've just been trying to install Taxonomy on a system where I'm limited to installing via Conda. I eventually succeeded by installing Rust with Conda, then `pip` to install Taxonomy. But I noticed this left me with Taxonomy 0.9.0, rather than 0.10.0. It's not a big issue but I had a look at the files available on PyPI and noticed that there's no source distribution for Taxonomy 0.10.0 nor Python 3.12 wheels for any version. Could these be generated and uploaded to PyPI?

Searching the existing issues (open or closed) returned nothing for "3.12".

**Comment by jairideout** [comment]
Hi @warrickball! I built and uploaded the v0.10.0 source distribution and Python 3.12 wheels to PyPI. There's wheels for macOS and Linux, including x86 and ARM architectures. Let me know if you run into any issues!

**Comment by warrickball** [comment]
Brilliant! Thanks for such a quick response. I've just installed v0.10.0, which saves me implementing my own equivalent of `Taxonomy.descendants`.
